name: Format Check

on:
  pull_request:
    branches:
      - main  # PR이 요청될 대상 브랜치

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Java 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'  # 또는 'zulu', 'temurin' 등 사용하고자 하는 배포판 선택


      # 3. Google Java Format 다운로드
      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/latest/download/google-java-format-1.23.0-all-deps.jar -O google-java-format.jar
      #          wget https://github.com/google/google-java-format/releases/latest/download/google-java-format-<version>-all-deps.jar -O google-java-format.jar

      # 4. 포맷 검사 실행
      - name: Run Google Java Format Check
        run: |
          java -jar google-java-format.jar --replace $(git ls-files '*.java')

      # 5. 변경 사항 커밋
      - name: Commit changes
        run: |
          git config --local user.name "hyunjinkim-kr"
          git config --local user.email "dufqnfsk22@gmail.com"
          git add .
          git commit -m "Apply Google Java Format" || echo "No changes to commit"
          git push
