name: Format and Build Check

on:
  pull_request:
    branches:
      - main  # PR이 요청될 대상 브랜치

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Java 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      # 3. Google Java Format 다운로드
      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/latest/download/google-java-format-1.23.0-all-deps.jar -O google-java-format.jar

      # 4. 포맷 검사 실행
      - name: Run Google Java Format Check
        run: |
          # 현재 브랜치에서 변경된 Java 파일을 가져옵니다.
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACM origin/main...HEAD | grep '.java$')
          echo "Changed files: $CHANGED_FILES"  # 변경된 파일 출력
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files changed in this PR."
          else
            for file in $CHANGED_FILES; do
              OUTPUT=$(java -jar google-java-format.jar --dry-run "$file")
              if [ -n "$OUTPUT" ]; then
                echo "Formatting issues found in $file:"
                echo "$OUTPUT"
                echo "Please fix the formatting issues in $file before pushing."
                exit 1
              fi
            done
            echo "All Java files are formatted correctly."
          fi

      # 5. 직접 Java 컴파일
      - name: Compile Java files
        run: |
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files to compile."
          else
            for file in $CHANGED_FILES; do
              javac "$file"
              if [ $? -ne 0 ]; then
                echo "Compilation failed for $file."
                exit 1
              fi
            done
            echo "All Java files compiled successfully."
          fi
