name: Format and Build Check

on:
  pull_request:
    branches:
      - main  # PR이 요청될 대상 브랜치

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 히스토리를 가져옵니다.

      # 2. Main 브랜치를 fetch
      - name: Fetch main branch
        run: |
          git fetch origin main

      # 3. Java 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      # 4. Google Java Format 다운로드
      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/download/v1.23.0/google-java-format-1.23.0-all-deps.jar -O google-java-format.jar

      # 5. 포맷 검사 실행
      - name: Run Google Java Format Check
        run: |
          # 현재 브랜치에서 변경된 Java 파일을 가져옵니다.
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '.java$' || true)
          echo "Changed files: $CHANGED_FILES"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files changed in this PR."
          else
            FORMAT_ISSUE_FOUND=false
            for file in $CHANGED_FILES; do
              # 파일을 포맷하고 변경 사항을 git diff로 확인
              java -jar google-java-format.jar "$file"
              if [ -n "$(git diff "$file")" ]; then
                echo "Formatting issues found in $file:"
                git diff "$file"
                FORMAT_ISSUE_FOUND=true
              fi
            done
            if [ "$FORMAT_ISSUE_FOUND" = true ]; then
              echo "Formatting issues detected. Please fix them before pushing."
              exit 1
            else
              echo "All Java files are formatted correctly."
            fi
          fi

      # 6. 빌드 테스트 실행
      - name: Build the project
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew build  # Gradle 프로젝트인 경우
          else
            echo "Gradle wrapper not found, attempting Maven build..."
            mvn clean install  # Maven 프로젝트인 경우
