name: Format and Build Check

on:
  pull_request:
    branches:
      - main  # PR이 요청될 대상 브랜치

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Java 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      # 3. Google Java Format 다운로드
      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/latest/download/google-java-format-1.23.0-all-deps.jar -O google-java-format.jar

      # 4. 포맷 검사 실행 dev -> main
      - name: Run Google Java Format Check
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main...dev | grep '.java$')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files changed in this PR."
          else
            java -jar google-java-format.jar --dry-run $CHANGED_FILES
          fi

      # 5. 포매팅 실패시 오류 반환
      - name: Fail if formatting issues are found
        if: ${{ failure() }}
        run: |
          echo "Formatting issues found. Please fix them before pushing."

      # 6. 빌드 테스트 실행
      - name: Build the project
        run: |
          ./gradlew build  # Gradle 프로젝트인 경우. Maven 프로젝트일 경우 'mvn clean install' 사용

